FROM node:20.15.0 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# docker-compose-prod에 명시된 args(변수)를 이미지 빌드시 환경 변수로 사용한다.
ARG REACT_APP_NAME
ENV REACT_APP_NAME=${REACT_APP_NAME}
# 인수를 환경 변수에 할당하는 순서를 잘 지켜야 한다.
ARG REACT_APP_TITLE
ENV REACT_APP_TITLE=${REACT_APP_TITLE}

RUN npm run build

# 빌드된 파일을 호스트의 Nginx 데이터 디렉토리로 복사
RUN mkdir -p /home/ubuntu/nginx-data/html
RUN cp -r /app/dist/* /home/ubuntu/nginx-data/html/
